import { Josefin_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import Link from 'next/link';
import React from 'react';

import ClientError from '@/components/GlobalError';
import Provider from '@/components/Provider';
import { cn } from '@/lib/utils';

import './globals.css';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['700'],
});

export const metadata: Metadata = {
  title: 'Crypto Base',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="min-h-screen">
        <Provider>
          <header className="border-b p-3">
            <Link href="/">
              <h1
                className={cn(
                  `${josefinSans.className}`,
                  'text-center text-2xl'
                )}
              >
                Crypto Base
              </h1>
            </Link>
          </header>
          <main className="h-full w-full">{children}</main>
          <ClientError />
        </Provider>
      </body>
    </html>
  );
}
